name: Deploy Bytedevs.com to Firebase Hosting

on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_live_website:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npx nx run bytedevs:build && npx nx run blink-website:build

      # TODO: We should use NX to determine which projects to deploy
      #       and deploy only those projects that have changed.
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BYTEDEVS_57983 }}
          # TODO: get this token from config/secrets instead of hardcoding
          projectId: bytedevs-57983
          channelId: live
